policies:
  - name: KerasPolicy
    epochs: 200
    max_history: 5
    random_seed: 1
#  - name: EmbeddingPolicy
#    epochs: 100
#    random_seed: 1
  - name: MemoizationPolicy
    max_history: 5
  - name: FormPolicy
  - name: FallbackPolicy
    nlu_threshold: 0.7
    core_threshold: 0.7
    fallback_action_name: 'action_default_fallback'