# config file from https://rasa.com/docs/core/installation/

version: '3.0'

services:
  rasa_core:
    image: rasa/rasa_core:latest
    networks: ['rasa-network']
    ports:
    - "5005:5005"
    volumes:
    - "./chat_bot/models/current/dialogue:/app/model"
    - "./chat_bot/config:/app/config"
    - "./chat_bot/project:/app/project"
    command: start -d ./models -c rest -u current/nlu --endpoints config/endpoints.yml
#    - start
#    - -d
#    - ./models
#    - -c
#    - rest
#    - -u
#    - current/nlu
#    - --endpoints
#    - config/endpoints.yml

  action_server:
    image: rasa/rasa_core_sdk:latest
    networks: ['rasa-network']
    ports:
    - "5055:5055"
    volumes:
    - "./rasa-app-data/actions:/app/actions"

  rasa_nlu:
    image: rasa/rasa_nlu:latest-full
    networks: ['rasa-network']
    ports:
    - "5000:5000"
    volumes:
    - "./chat_bot/models/:/app/projects"
    - "./chat_bot/logs:/app/logs"

  duckling:
    image: rasa/duckling:latest
    networks: ['rasa-network']
    ports:
    - "8000:8000"

#networks: {rasa-network: {}}
networks:
    default:
      name: 'rasa-network'